/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PacienteController;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.Paciente;

/**
 *
 * @author matheusnascimento
 */
public class ListReportView extends javax.swing.JFrame {

    private String baseUrl;
    private PacienteController reportController;
    private boolean exitThread;

    /**
     * Creates new form ListReportView
     *
     * @param baseUrl
     */
    public ListReportView(String baseUrl) {
        initComponents();
        this.exitThread = false;
        this.baseUrl = baseUrl;
        reportController = new PacienteController();
        Thread threadListPacientes = new Thread(listPacientes, "Listagem pacientes");
        threadListPacientes.start();

    }

    Runnable listPacientes
            = new Runnable() {
        @Override
        public void run() {
            System.out.println("Runnable running");

            while (!exitThread) {
                try {

                    Paciente[] pacientes = reportController.listPaciente(baseUrl);
                    DefaultTableModel model = (DefaultTableModel) tblPacientes.getModel();
                    model.setRowCount(0);
                    for (Paciente paciente1 : pacientes) {
                        Object[] row = {
                            paciente1.getNome(),
                            paciente1.getCpf(),
                            paciente1.getPressaoArterial(),
                            paciente1.getFreqCardiaca(),
                            paciente1.getTemperatura(),
                            paciente1.getSaturacao(),
                            paciente1.getGravidade()
                        };
                        model.addRow(row);
                        System.out.println("Nome: " + paciente1.getNome());
                    }
                    Thread.sleep(10000);
                } catch (Exception e) {
                }
            }

        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Pressão Arterial", "Bpm", "Temperatura", "Saturacao", "Gravidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPacientes);

        jLabel1.setText("Pacientes monitorados ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        String cpf = source.getModel().getValueAt(row, 1) + "";
        Paciente paciente = reportController.getPaciente(baseUrl, cpf);
        if (paciente != null) {
            exitThread = true;
            ReportView reportView = new ReportView(paciente, baseUrl);
            reportView.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_tblPacientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPacientes;
    // End of variables declaration//GEN-END:variables
}
