/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PacienteController;
import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.Paciente;

/**
 *
 * @author matheusnascimento
 */
public class ReportView extends javax.swing.JFrame {

    private String baseUrl;
    private Paciente paciente;
    private PacienteController reportController;
    private boolean exitThread;
    /**
     * Creates new form ReportView
     */
    public ReportView(Paciente paciente, String baseUrl) {
        this.baseUrl = baseUrl;
        initComponents();
        this.exitThread = false;
        this.paciente = paciente;
        spnGravidade.setValue(paciente.getGravidade());
        reportController = new PacienteController();
        Thread threadMonitorarPaciente = new Thread(monitorarPaciente, "Monitoramento");
        threadMonitorarPaciente.start();

    }

    Runnable monitorarPaciente
            = new Runnable() {
        public void run() {
            System.out.println("Runnable running");

            try {
                while (!exitThread) {
                    paciente = reportController.getPaciente(baseUrl, paciente.getCpf());
                    tfFreqCardiaca.setText(paciente.getFreqCardiaca());
                    tfPressao.setText(paciente.getPressaoArterial());
                    tfTemperatura.setText(paciente.getTemperatura() + "");
                    tfSaturacao.setText(paciente.getSaturacao());
                    lbNome.setText("Paciente: " + paciente.getNome());
                    Thread.sleep(500);
                }
            } catch (InterruptedException e) {
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        tfTemperatura = new javax.swing.JTextField();
        tfFreqCardiaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPressao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSaturacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnUpdateGravidade = new javax.swing.JButton();
        lbSituacao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        spnGravidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNome.setText("Paciente");

        tfTemperatura.setFocusable(false);
        tfTemperatura.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfTemperaturaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tfTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTemperaturaActionPerformed(evt);
            }
        });
        tfTemperatura.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfTemperaturaPropertyChange(evt);
            }
        });
        tfTemperatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTemperaturaKeyPressed(evt);
            }
        });

        tfFreqCardiaca.setFocusable(false);
        tfFreqCardiaca.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfFreqCardiacaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tfFreqCardiaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFreqCardiacaActionPerformed(evt);
            }
        });
        tfFreqCardiaca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfFreqCardiacaPropertyChange(evt);
            }
        });
        tfFreqCardiaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFreqCardiacaKeyPressed(evt);
            }
        });

        jLabel2.setText("Temperatura (ºC)");

        jLabel3.setText("Frequência Cardíaca (bpm)");

        tfPressao.setFocusable(false);
        tfPressao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfPressaoPropertyChange(evt);
            }
        });
        tfPressao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPressaoKeyPressed(evt);
            }
        });

        jLabel4.setText("Pressão Arterial (mmHg)");

        tfSaturacao.setFocusable(false);
        tfSaturacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaturacaoActionPerformed(evt);
            }
        });
        tfSaturacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSaturacaoKeyPressed(evt);
            }
        });

        jLabel5.setText("Saturação (% SpO2)");

        btnUpdateGravidade.setText("Reportar");
        btnUpdateGravidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateGravidadeMouseClicked(evt);
            }
        });
        btnUpdateGravidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGravidadeActionPerformed(evt);
            }
        });

        lbSituacao.setText("Gravidade: ");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        spnGravidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnGravidadeStateChanged(evt);
            }
        });
        spnGravidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spnGravidadeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPressao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSaturacao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addComponent(tfTemperatura, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFreqCardiaca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(60, 60, 60)))
                                .addGap(8, 8, 8)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbSituacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnGravidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateGravidade)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnGravidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateGravidade)))
                .addGap(9, 9, 9)
                .addComponent(tfTemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(tfFreqCardiaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(tfPressao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(tfSaturacao)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemperaturaActionPerformed

    private void tfFreqCardiacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFreqCardiacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFreqCardiacaActionPerformed

    private void tfSaturacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaturacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaturacaoActionPerformed

    private void btnUpdateGravidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGravidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateGravidadeActionPerformed

    private void btnUpdateGravidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateGravidadeMouseClicked
        // TODO add your handling code here:
        btnUpdateGravidade.setText("Enviando...");
        paciente.setGravidade((int)spnGravidade.getValue());
        Boolean status = reportController.updateGravidadePaciente(baseUrl, paciente.toString());
        if (!status) {
            btnUpdateGravidade.setBackground(Color.RED);
        } else {
            btnUpdateGravidade.setBackground(Color.GREEN);
        }
        btnUpdateGravidade.setText("Reportar");

    }//GEN-LAST:event_btnUpdateGravidadeMouseClicked

    private void tfTemperaturaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfTemperaturaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemperaturaPropertyChange

    private void tfFreqCardiacaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfFreqCardiacaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFreqCardiacaPropertyChange

    private void tfPressaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfPressaoPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_tfPressaoPropertyChange

    private void tfTemperaturaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfTemperaturaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemperaturaInputMethodTextChanged

    private void tfFreqCardiacaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfFreqCardiacaInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_tfFreqCardiacaInputMethodTextChanged

    private void tfTemperaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTemperaturaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfTemperaturaKeyPressed

    private void tfFreqCardiacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFreqCardiacaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfFreqCardiacaKeyPressed

    private void tfPressaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPressaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPressaoKeyPressed

    private void tfSaturacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSaturacaoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfSaturacaoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ListReportView reportView = new ListReportView(baseUrl);
        reportView.setVisible(true);
        exitThread = true;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spnGravidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnGravidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spnGravidadeMouseClicked

    private void spnGravidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnGravidadeStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spnGravidadeStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateGravidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSituacao;
    private javax.swing.JSpinner spnGravidade;
    private javax.swing.JTextField tfFreqCardiaca;
    private javax.swing.JTextField tfPressao;
    private javax.swing.JTextField tfSaturacao;
    private javax.swing.JTextField tfTemperatura;
    // End of variables declaration//GEN-END:variables
}
